### PR TITLE
Introduce site overlays

### PR DESCRIPTION
**Pull request by mslacken**
site overlays are placed in sysconfdir/overlays and take
precedence over distribution overlays with the same name.

Every wwctl overlay command changing overlays will create
an site overlay. distribution overlays can't be deleted or
modified with wwctl.

### CODE REVIEW

**Comment by anderbubble** [comment]
Rebased to main.

**Comment by anderbubble** [comment]
The decision in the 7 August 2024 TSC meeting was to use

- `/usr/share/warewulf/overlays` for distribution overlays
- `/var/lib/warewulf/overlays` for site overlays

(I'll work on making this adjustment; but recording here for future reference.)

**Comment by anderbubble** [comment]
@mslacken I added additional commits at https://github.com/anderbubble/warewulf/tree/SeperateUserOverlays:

- move overlays to the locations decided in a previous TSC meeting
- fix packaging
- refactor overlays around a new type
- further documentation edits
- add tests
- bugfixes

Let me know what you think. If you approve, I'll push those commits here and merge.

**Comment by anderbubble** [comment]
Actually, I'll go ahead and push to the PR 'cause it's easier to inspect that way. We can always remove or change them if necessary.

**Review by mslacken — COMMENTED** [review]
Looks, goo. We can merge that one.

**Review by anderbubble — APPROVED** [review]

**Pull request merged**
