### PR TITLE
upgrade minimum golang version to 1.19 and golangci-lint version to 1.56.2

### LINKED ISSUE #1096: Resolve security-related dependabot issues
Dependabot is reporting issues with Warewulf. It as already generated a few PRs, but it will do more as we complete those which are already submitted.

https://github.com/warewulf/warewulf/security/dependabot

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Several dependabot created PRs require minimum golang version of 1.19
```
Run make vet
fatal: No names found, cannot describe anything.
go vet ./...
# github.com/klauspost/compress/zstd
Error: vendor/github.com/klauspost/compress/zstd/dict.go:[4](https://github.com/warewulf/warewulf/actions/runs/7999361562/job/21847043335?pr=1103#step:4:5)79:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: vendor/github.com/klauspost/compress/zstd/dict.go:490:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: vendor/github.com/klauspost/compress/zstd/dict.go:491:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
Error: vendor/github.com/klauspost/compress/zstd/dict.go:492:32: binary.LittleEndian.AppendUint32 undefined (type binary.littleEndian has no field or method AppendUint32)
note: module requires Go 1.19
# github.com/docker/docker-credential-helpers/client
Error: vendor/github.com/docker/docker-credential-helpers/client/command.go:34:39: programCmd.Environ undefined (type *exec.Cmd has no field or method Environ)
note: module requires Go 1.19
# google.golang.org/grpc
Error: vendor/google.golang.org/grpc/server.go:2096:14: undefined: atomic.Int64
note: module requires Go 1.19
make: *** [Makefile:7[5](https://github.com/warewulf/warewulf/actions/runs/7999361562/job/21847043335?pr=1103#step:4:6): vet] Error 2
Error: Process completed with exit code 2.
```

These PRs are:
https://github.com/warewulf/warewulf/pull/1103
https://github.com/warewulf/warewulf/pull/1102
https://github.com/warewulf/warewulf/pull/1044

PRs created by dependabot are here
https://github.com/warewulf/warewulf/pulls/app%2Fdependabot

Besides golangci-lint version also needs to upgrade in order to run successfully on golang version 1.21. 

## This fixes or addresses the following GitHub issues:

 - Fixes #1096

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
I've confirmed that even CentOS 7 has go 1.20.10 in EPEL, so I think this should be fine; but I'll check with TSC to make sure before we proceed.

**Comment by JasonYangShadow** [comment]
@anderbubble is TSC okay with this upgrade?

**Review by mslacken — APPROVED** [review]
thx

**Comment by mslacken** [comment]
@JasonYangShadow Can you add a CHANGELOG entry?

**Pull request merged**
