### PR TITLE
Replace ref to docusaurus with Sphinx

### PR DESCRIPTION
**Pull request by griznog**

### CODE REVIEW

**Comment by mslacken** [comment]
I don't see the actual change, just the update in the documentation

**Comment by griznog** [comment]
I'm not sure what I did wrong here, I thing `git` is gaslighting me. Locally I see this:

```
griznog@corbicula:userdocs$ git show 
commit 65b696151b0aeb3555aeeb1ba6d7c4802a5e8157 (HEAD -> we-use-sphinx-now, fork/we-use-sphinx-now)
Author: griznog <griznog@gmail.com>
Date:   Thu May 23 16:43:59 2024 -0700

    Replace ref to docusaurus with Sphinx.

diff --git a/CHANGELOG.md b/CHANGELOG.md
index e682910c..da3f96d0 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -8,6 +8,7 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).
 
 ### Added
 
+- Replace reference to docusaurus with Sphinx
 - Add the ability to boot nodes with `wwid=[interface]`, which replaces
   `interface` with the interface MAC address
 - Added https://github.com/Masterminds/sprig functions to templates #1030
diff --git a/userdocs/contributing/documentation.rst b/userdocs/contributing/documentation.rst
index 17100d9b..6ae8e012 100644
--- a/userdocs/contributing/documentation.rst
+++ b/userdocs/contributing/documentation.rst
@@ -13,8 +13,8 @@ suggest an improvement
 `pull request <https://github.com/warewulf/warewulf-web/compare>`_ on
 `our repository <https://github.com/warewulf/warewulf-web>`_.
 
-The current documentation is generated with `Docusaurus
-<https://v2.docusaurus.io/docs/>`_.
+The current documentation is generated with `Sphinx
+<https://www.sphinx-doc.org/en/master/>`_.
 
 For more information on using Git and GitHub to create a pull request
 suggesting additions and edits to the docs, see the `section on
griznog@corbicula:userdocs$ git status
On branch we-use-sphinx-now
Your branch is up to date with 'fork/we-use-sphinx-now'.

nothing to commit, working tree clean
griznog@corbicula:userdocs$ git push
Everything up-to-date
```

**Comment by griznog** [comment]
There wasn't anything to change in the Makefile, just needed to fix the docs where that one reference to docusaurus was at. But when I opened it all I saw was the CHANGELOG.md changes. User error on my part, I think. SHould be good to go now.

**Comment by anderbubble** [comment]
Rebased on main.

**Review by anderbubble — APPROVED** [review]
I made some small changes and dropped the unnecessary whitespace-only commit; but lgtm now.

**Comment by anderbubble** [comment]
Backported to v4.5.x.

**Pull request merged**
