### PR TITLE
Fix grub asset key handling

### PR DESCRIPTION
**Pull request by epruesse**
## Description of the Pull Request (PR):

This fixes asset key retrieval in the rendered grub.cfg and adds it to the chainload grub.cfg, allowing asset key based grub boot to work. 

- `--type1` should be `--type 1`
- The `chassis-asset-tag` (as used elsewhere), is not in the type 1 tabke, but in the type 3 table. 
- If an asset tag is listed in the node config, it is checked by wwctl server on all requests, so everything using `(http,<ip:port)` must also use `?assetkey=${assetkey}`, including fetching the templated grub.cfg. 

Note that this is not a full fix. The grub.efi files supplied with Rocky 9.4 do not include the `smbios` command! This has been the case for many years, apparently. I have used a Debian box to run `grub2-makenetdir`, generating a working grub efi.

With that, it is now working.

For testing, you can add an asset key to a KVM VM like this:

```
qm set $VMID --args "-smbios type=3,asset=$KEY"
```

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by epruesse** [comment]
@anderbubble Do you want me to add a comment to the docs about having to use the Debian Grub? IDK how else to fix this. If you go into the grub shell and type "smbios", it'll tell you the function isn't there with the regular Rocky 9.4 grub package. There is no error shown for this when running the config. It just leads to an empty $assetkey variable.

**Comment by anderbubble** [comment]
@epruesse I haven't dug into this myself yet, so I'm not certain, and I'd be interested to hear @mslacken's perspective especially, since he developed this originally.

I don't think we'd want to be dependent on a specific OS's grub.

**Comment by epruesse** [comment]
Well, depending on OS packages to have the correct features compiled in can't really be avoided. Do you have influence with the Rocky maintainers or better yet upstream with RHEL?

I don't see many alternatives for having a secret shared with a diskless server other than values like this. Although I suppose the entire security concept could be reevaluated.

**Comment by anderbubble** [comment]
@mslacken can you review this?

**Review by mslacken — APPROVED** [review]
thx

**Pull request merged**
