### PR TITLE
Configure nodes.conf dynamically from config

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

Removes the use of init() to initialize the path to `nodes.conf`, replacing it with a dynamic lookup from config.

- Closes: #1596 
- See also: #1569

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [ ] The test suite has been updated, if necessary

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken can you review this as an alternative to #1569?

There you mentioned

> The location for nodes.conf can be given [as] a command line parameter

If you can point out a place still impacted by this problem, I'll try to resolve it; but I think this is significantly simpler than the current state of #1569.

**Review by mslacken — CHANGES_REQUESTED** [review]
Doesn't close #1596 so please close this one and merge #1569

init() is always called *before* the command line values are evaluated. Setting any path related values there just make things complicated.

**Comment by anderbubble** [comment]
@mslacken thanks for #1596, and for the discussion there. I definitely hadn't understood what you were expecting to work, or why.

Forgive me if I've basically just reimplemented what you did in #1569 here, now; but I _think_ this is simpler (or, maybe, just organized in a way I prefer), and appears to fix #1596. Give it a look if you have time, and we can discuss further if necessary in the meeting.

**Review by JasonYangShadow — APPROVED** [review]
Thanks! This PR makes the code easier to understand, empty init() should be removed. For test env's nodes.config, I personally feel that keeping the original `/etc/warewulf/nodes.conf` is easier to read especially under the below situation
msedge_qLzL5zHVBB
where all configurations are raw paths.

**Comment by anderbubble** [comment]
@mslacken looks like this still needs your explicitly approval before it can be merged, since you requested changes.

**Review by mslacken — APPROVED** [review]

**Comment by mslacken** [comment]
Thanks for also cleaning up all the test code.

**Comment by anderbubble** [comment]
Thanks for the merge!

**Pull request merged**
