### PR TITLE
Fixes  POSIX syntax for several scripts #1464 

### LINKED ISSUE #1464: POSIX syntax for several scripts
### Summary

While building and testing WW4 under Ubuntu 22.04 LTS and 24.04 LTS, it was discovered that several scripts broke due to Ubuntu/Debian use of /bin/dash instead of /bin/bash for /bin/sh. The scripts are:

overlays/wwinit/rootfs/warewulf/wwinit
overlays/wwinit/rootfs/init
scripts/build-ipxe.sh

### Rationale

Since Ubuntu and Debian both use dash, POSIX compliance is warranted. A simple workaround would be to force the use of bash, however, POSIX compliance is preferred in the event that bash is not available on the system, or some other environment requires it.

### Description

I have modified versions of the aforementioned scripts for POSIX compliance. Additionally, I have added commented out logic in the wwinit script to facilitate testing for the .sh suffix and exec bit on the scripts launched should that become needed.

### Additional information

_No response_

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by iankgt40**
## Description of the Pull Request (PR):
While building and testing WW4 under Ubuntu 22.04 LTS and 24.04 LTS, it was discovered that several scripts broke due to Ubuntu/Debian use of /bin/dash instead of /bin/bash for /bin/sh. The scripts are:

overlays/wwinit/rootfs/warewulf/wwinit
overlays/wwinit/rootfs/init
scripts/build-ipxe.sh

Since Ubuntu and Debian both use dash, POSIX compliance is warranted. A simple workaround would be to force the use of bash, however, POSIX compliance is preferred in the event that bash is not available on the system, or some other environment requires it.

I have added commented out logic in the wwinit script to facilitate testing for the .sh suffix and exec bit on the scripts launched should that become needed.

## This fixes or addresses the following GitHub issues:

- Fixes #1464 
[wwinit.txt](https://github.com/user-attachments/files/17576207/wwinit.txt)
[init.txt](https://github.com/user-attachments/files/17576208/init.txt)
[build-ipxe-with-read.sh.txt](https://github.com/user-attachments/files/17576209/build-ipxe-with-read.sh.txt)

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [x] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [x] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [x] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [x] The test suite has been updated, if necessary

### CODE REVIEW

**Comment by anderbubble** [comment]
@iankgt40 thanks for submitting!

This PR needs to be rebased onto main, removing the intermediate merges along the way. I'll try to do that myself and let you know if I run into any trouble.

**Comment by iankgt40** [comment]
Ugh ... sorry. And I had to add the ".txt" to get the files submitted ...

Ian

Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________

**Comment by anderbubble** [comment]
@iankgt40 it looks like this PR doesn't actually contain the new files. (I see them attached to the GitHub description; but that's different.)

If you're having trouble with Git, I can craft a new PR with the files you attached and get it in front of you to make sure it's what you're after.

Let me know what you'd prefer.

**Review by anderbubble — CHANGES_REQUESTED** [review]
PR needs to be based on main and include changed files. Current PR merges unmodified main into v4.5.x.

**Comment by iankgt40** [comment]
gh pr update-branch 1475 or gh pr merge 1475 - do you have a preference?

Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________

**Comment by iankgt40** [comment]
I have uploaded the files into my branch, but the PR isn't letting me change to main ...

**Comment by iankgt40** [comment]
Figured it out ... everything is ready for review

**Comment by anderbubble** [comment]
Thank you! I'll review.

**Comment by iankgt40** [comment]
Sorry it took so long ... I haven't been involved in a project of such scope in forever ...

Mostly just private stuff, or a very small group.

However, that is changing ...

Ian

Ian Kaufman
Systems Integration Engineer
UC San Diego, Research IT Services
ikaufman AT ucsd DOT edu
________________________________

**Review by anderbubble — APPROVED** [review]
I made a few changes, but I think it's good to go now.

Thanks, @iankgt40!

Recommendations for future contributions:

- submit PRs from a branch other than your `main`. (They should be submitted _to_ `main`, though.)
- sign-off on your commits with `git commit --signoff`

**Pull request merged**
