### PR TITLE
Enable nested profiles

### PR DESCRIPTION
**Pull request by griznog**
- **Move Profiles from Node struct to Profile struct.**
- **Enable/handle nested profiles.**
- **Add test for merged profile tags.**
- **Update CHANGELOG.md**

## Description of the Pull Request (PR):

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

## This fixes or addresses the following GitHub issues:

- Fixes #

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [ ] The test suite has been updated, if necessary

### CODE REVIEW

**Comment by griznog** [comment]
When I `make test` there are a lot of failing tests, some of which look like they might be related to moving `Profiles` from the `Node` struct to the `Profile` struct, but a whole lot more that don't seem to be related. I must shamefully admit that today is the first time I've ran `make test` locally so I don't know how normal the failed tests are or if they are just something I have broken locally on my system. 

@anderbubble let me know if my test is ok, I think I want to add some more checks to it around tags/values in netdev and ipmi, but wanted to start simple.

**Comment by mslacken** [comment]
Using the profile name as sorting order sound arbitrary and I don't like the idea. Still it might be the best solution as
# users can change the order by renaming the profile, like in `init.d`
# its predictable all the time
@anderbubble what's your take?

**Comment by griznog** [comment]
@mslacken I played a little with the idea of building a graph and merging profiles in the order they are specified/included, but eventually settled on the approach of flattening the list of profiles and sorting as a compromise that makes it easy to understand how the merging is done and easier to control the order in the case someone wants to do that. 

In my local WW foo I've found that both overlays and profiles work much better and much more understandably if I stick to the best practice of never setting the same value in multiple profiles and never letting two included overlays touch/modify the same file. The further I go down the profile/overlay rabbit hole the more I lean toward detecting either of those things happening and throwing an error or at least a warning when it does happen as it, at least in my experience, always leads to confusion and regret when it happens.

**Comment by griznog** [comment]
This still needs some work. Tags merge correctly but overlays are not appending correctly, presumably `mergo` is not doing what I think it is doing.

**Pull request closed without merging**
