### PR TITLE
Make mounting into sub-directoies work

### LINKED ISSUE #1073: mounting of local partitions into sub-directories is not working
### Steps to reproduce

Having a local fs mounted under a 2nd level directory (see below) is not working.

```
    filesystems:
      /dev/disk/by-partlabel/scratch:
        format: xfs
        path: /local/scratch
        wipe_filesystem: "true"
```

### Error message

systemd unit logs:
```Where= setting doesn't match unit name. Refusing.```

see also:
<https://unix.stackexchange.com/questions/283442/systemd-mount-fails-where-setting-doesnt-match-unit-name>

### Information on your system

```
[root@leto ~]# wwctl version 
wwctl version:   4.5.x-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.x-1"

[root@leto ~]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by riederd**
## Description of the Pull Request (PR):

Fix mounting local partitions into sub directoies.

## This fixes or addresses the following GitHub issues:

 - Fixes #1073

### CODE REVIEW

**Comment by riederd** [comment]
Sorry, I accidentally pushed the networkmanager config improvement to this pull request.

**Review by mslacken — APPROVED** [review]
@riederd I fore pushed to get rid of the Network Manager stuff. So if this changes aren't in another PR, don't update your main, before you branched of your changes.
Thanks, for this PR, it works now as expected.

**Comment by anderbubble** [comment]
@mslacken should this go into v4.5.0, kept back for v4.5.1, or kept back for v4.6.0?

**Comment by mslacken** [comment]
I merged it as it should go in 4.5.0 as not being able to mount into sub directories is a major bug.

**Pull request merged**
