### PR TITLE
add DNS fields to multiple managed templates

### LINKED ISSUE #922: Configure DNS resolution on the compute node
In the past, resolv.conf was copied from the host into the the node image during container import. However, this has recently been replaced by read-only bind mounts.

We should add resolv.conf back into the container image by way of the wwinit overlay, just importing the contents of the file from the host by default.

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

now if the NetDev tags contain keys with prefix "DNS", it'll be copied into the ifcfg.ww template.

## This fixes or addresses the following GitHub issues:

 - Fixes #922

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

## Test
```
[root@localhost warewulf]# cat /usr/local/etc/warewulf/nodes.conf 
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
nodes:
  n1:
    profiles:
    - default
    network devices:
      dummy:
        tags:
          DNS1: 1.1.1.1
          DNS2: 8.8.8.8

[root@localhost warewulf]# wwctl overlay show -r n1 wwinit /etc/sysconfig/network-scripts/ifcfg.ww
backupFile: true
writeFile: true
Filename: ifcfg-dummy.conf

# This file is autogenerated by warewulf
# Host:   localhost.localdomain
# Time:   02-07-2024 05:00:35 MST
# Source: /var/local/warewulf/overlays/wwinit/etc/sysconfig/network-scripts/ifcfg.ww
TYPE=ethernet
DEVICE=eth0
NAME=dummy
BOOTPROTO=static
DEVTIMEOUT=10
IPADDR=
NETMASK=255.255.255.0
TYPE=ethernet
ONBOOT=true
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
DNS1=1.1.1.1
DNS2=8.8.8.8

[root@localhost warewulf]# wwctl overlay show -r n1 wwinit /etc/resolv.conf.ww
backupFile: true
writeFile: true
Filename: /etc/resolv.conf

# This file is autogenerated by warewulf
# Host:   localhost.localdomain
# Time:   02-07-2024 17:37:49 MST
# Source: /var/local/warewulf/overlays/wwinit/etc/resolv.conf.ww
nameserver 1.1.1.1
nameserver 8.8.8.8

[root@localhost warewulf]# wwctl overlay show -r n1 wwinit /etc/NetworkManager/system-connections/ww4-managed.ww
backupFile: true
writeFile: true
Filename: warewulf-dummy.conf
# This file is autogenerated by warewulf
# Host:   localhost.localdomain
# Time:   02-07-2024 17:38:04 MST
# Source: /var/local/warewulf/overlays/wwinit/etc/NetworkManager/system-connections/ww4-managed.ww
[connection]
id=dummy
interface-name=eth0
type=ethernet
autoconnect=true

[ipv4]
address=<nil>
method=manual
dns=1.1.1.1;8.8.8.8;

[ipv6]
addr-gen-mode=stable-privacy
method=ignore
never-default=true
```

### CODE REVIEW

**Review by anderbubble — CHANGES_REQUESTED** [review]
Let's add support for this in NetworkManager as well, and also write out /etc/resolv.conf just in case.

**Comment by JasonYangShadow** [comment]
> Let's add support for this in NetworkManager as well, and also write out /etc/resolv.conf just in case.

I updated and added two other templates.

**Comment by alansill** [comment]
Just a ping on this. Would you like a tester?

**Comment by anderbubble** [comment]
Rebased to main.

**Review by anderbubble — APPROVED** [review]
These all appear to work correctly. Thanks!

**Pull request merged**
