### PR TITLE
allow rendering of host templates

### LINKED ISSUE #623: wwctl overlay show --render for host templates
`wwctl overlay show --render` supports rendering templates for "nodes" but not for the host overlay. There should be a way to do that.

### PR DESCRIPTION
**Pull request by mslacken**
Allow rendering of host templates where `-r host` or even `-r $(uname -n)` are now 
valid flags for `-r`.

- Closes #623

### CODE REVIEW

**Comment by anderbubble** [comment]
Implements #623

**Comment by anderbubble** [comment]
Closes #623

**Comment by JasonYangShadow** [comment]
@mslacken I am testing this PR
it looks like the code will always fail.
```
NodeName != "host" || NodeName != localHostname
```
the value of  `localHostname` of my test env is `localhost.localdomain`. 
from the code, this condition will always be true, because NodeName can not equal both `host and localHostname`?

**Comment by mslacken** [comment]
> @mslacken I am testing this PR it looks like the code will always fail.
> 
> ```
> NodeName != "host" || NodeName != localHostname
> ```
> 
> the value of `localHostname` of my test env is `localhost.localdomain`. from the code, this condition will always be true, because NodeName can not equal both `host and localHostname`? this will always generate the following error
> 
> ```
> ERROR  : xxx does not identify a single node
> ```

Right, I am just a physcist so I hoped this could be solved by a schrödingers inequality

**Comment by mslacken** [comment]
merged via #1153

**Pull request closed without merging**
