### PR TITLE
Fix boolean pointer handling

### LINKED ISSUE #1472: panic: reflect: NumField of non-struct type bool when onboot: true
### Steps to reproduce

```wwctl node list -a n1```

```
WW_INTERNAL: 43
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    container name: rocky-8
    system overlay:
    - wwinit
    - ifcfg
nodes:
  n1:
    comment: a node comment
    cluster name: mycluster
    kernel:
      args: crashkernel=no vga=791 net.naming-scheme=v238
    profiles:
    - default
    network devices:
      default:
        type: Ethernet
        onboot: true
        device: eth0
        hwaddr: a0:88:c2:03:00:d3
        ipaddr: 192.168.0.100
        netmask: 255.255.255.0
        gateway: 192.168.0.1
    tags:
      arch: x86_64
```

### Error message

```
panic: reflect: NumField of non-struct type bool

goroutine 1 [running]:
reflect.(*rtype).NumField(0x0?)
	/usr/lib/golang/src/reflect/type.go:762 +0x6c
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xf10340?, {0xf10340?, 0x4000313b0e?}, {0x400058d890, 0x18}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:90 +0x18c
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0x400061e050?, {0xfb6320?, 0x4000178410?}, {0x400058d878, 0x11}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:118 +0x1388
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xff6340?, {0xff6340?, 0x40003de190?}, {0x0, 0x0}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:106 +0x1a14
github.com/warewulf/warewulf/internal/pkg/node.fieldMap.recursiveFields(0xf9c8a0?, {0x1059280?, 0x40003de140?}, {0x0, 0x0}, {0x0, 0x0})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:115 +0x354
github.com/warewulf/warewulf/internal/pkg/node.(*NodeYaml).GetFields(_, {{0x4000312150, 0x2}, 0x1, {0x0, 0x0}, {0x0, 0x0}, {0x400036c350, 0x1, ...}, ...})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/node/list.go:51 +0x204
github.com/warewulf/warewulf/internal/pkg/api/node.NodeList(0x400061fbb0)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/pkg/api/node/list.go:88 +0x13ac
github.com/warewulf/warewulf/internal/app/wwctl/node/list.GetCommand.CobraRunE.func2(0x400015ea00?, {0x400059b820?, 0x1?, 0x2?})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/internal/app/wwctl/node/list/main.go:35 +0x13c
github.com/spf13/cobra.(*Command).execute(0x40005b2600, {0x400059b800, 0x2, 0x2})
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1a6de40)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(0x40000021a0?)
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/vendor/github.com/spf13/cobra/command.go:1039 +0x1c
main.main()
	/builddir/build/BUILD/warewulf-4.5.1test1+369.g9fc3ab71.dirty/cmd/wwctl/main.go:13 +0x24
```

Also setting `onboot: "true"` fails, but with a different error.

```
$ sudo wwctl node list -a n1
ERROR: yaml: unmarshal errors:
  line 20: cannot unmarshal !!str `true` into bool
```

### Information on your system

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

```
$ sudo wwctl version
wwctl version:	 4.5.1test1+369.g9fc3ab71.dirty-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.1test1+369.g9fc3ab71.dirty-1"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

- Refactor field reflection for clarity
- Update tests for clarity

## This fixes or addresses the following GitHub issues:

- Fixes #1472

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [x] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [x] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [x] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [x] The test suite has been updated, if necessary

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken I want to review this in the morning before a merge; but let me know if you have any feedback as it is right now.

**Comment by anderbubble** [comment]
@JasonYangShadow I added you as a reviewer since you encountered this or a similar issue. Let me know if this resolves your issue, and feel free to review / approve if you like it. :)

**Comment by anderbubble** [comment]
I had to fix a small bug in the PR; but I've provisioned a node with this now. I think it's good.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow I added you as a reviewer since you encountered this or a similar issue. Let me know if this resolves your issue, and feel free to review / approve if you like it. :)

will have a test on this today.

**Comment by JasonYangShadow** [comment]
looks like it is still having this error?
```
[root@warewulf vagrant]# wwctl node add n2
Added node: n2

[root@warewulf vagrant]# wwctl node edit n2
panic: reflect: NumField of non-struct type bool

goroutine 1 [running]:
reflect.(*rtype).NumField(0x0?)
        /usr/lib/golang/src/reflect/type.go:762 +0x59
github.com/warewulf/warewulf/internal/pkg/node.UnmarshalConf({0x1004280?, 0xc0003e22b8?}, {0xc0003f3958, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/internal/pkg/node/methods.go:227 +0xe4
github.com/warewulf/warewulf/internal/pkg/node.UnmarshalConf({0x118ae40?, 0xc00038a1a0?}, {0xc0003f3958, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/internal/pkg/node/methods.go:240 +0x4da
github.com/warewulf/warewulf/internal/pkg/node.UnmarshalConf({0x119c720?, 0xc0003e00e0?}, {0xc0003f3958, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/internal/pkg/node/methods.go:250 +0x733
github.com/warewulf/warewulf/internal/pkg/node.UnmarshalConf({0x1153a20?, 0xc0003f3af0?}, {0xc0003f3958, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/internal/pkg/node/methods.go:255 +0x7e6
github.com/warewulf/warewulf/internal/app/wwctl/node/edit.CobraRunE(0xc00028aa00?, {0xc000123db0, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/internal/app/wwctl/node/edit/main.go:54 +0x3fb
github.com/spf13/cobra.(*Command).execute(0x1b4f220, {0xc000123d70, 0x1, 0x1})
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/vendor/github.com/spf13/cobra/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0x1b48d80)
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/vendor/github.com/spf13/cobra/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/vendor/github.com/spf13/cobra/command.go:1039 +0x13
main.main()
        /home/vagrant/jonathon/warewulf-fix-bool-pointer/cmd/wwctl/main.go:13 +0x1e

[root@warewulf vagrant]# cat /usr/local/etc/warewulf/nodes.conf 
WW_INTERNAL: 46
nodeprofiles:
  default:
    comment: This profile is automatically included for each node
    container name: rocky-9
    ipxe template: default
    runtime overlay:
      - hosts
      - ssh.authorized_keys
      - syncuser
    system overlay:
      - wwinit
      - wwclient
      - fstab
      - hostname
      - ssh.host_keys
      - issue
      - resolv
      - udev.netname
      - systemd.netname
      - ifcfg
      - NetworkManager
      - debian.interfaces
      - wicked
      - ignition
    kernel:
      args: quiet crashkernel=no
    init: /sbin/init
    root: initramfs
    network devices:
      eth1:
        device: eth1
        netmask: 255.255.255.0
        gateway: 192.168.200.211
nodes:
  n1:
    profiles:
      - default
    network devices:
      eth1:
        hwaddr: 52:54:00:40:0a:67
  n2:
    profiles:
      - default
[root@warewulf vagrant]# 
```

**Comment by anderbubble** [comment]
> looks like it is still having this error?

I see it, too. Thanks for the catch.

**Comment by anderbubble** [comment]
@JasonYangShadow I think I fixed that issue now, too. Can you check again?

**Review by JasonYangShadow — APPROVED** [review]
node edit works now!

**Comment by anderbubble** [comment]
Thanks for the thorough review, @JasonYangShadow!

**Pull request merged**
