### PR TITLE
fix the bug that configuration expects CIDR format

### LINKED ISSUE #1016: ipaddr in configuration expecting CIDR notation
### Steps to reproduce

Configuration File (/etc/warewwulf/warewulf.conf)
```
dhcp:
    enabled: true
    range end: 10.0.1.255
    range start: 10.0.1.1
    systemd name: dhcpd
    template: default
ipaddr: 10.0.0.3
netmask: 255.255.252.0
nfs:
    enabled: true
    export paths:
    -   export options: rw,sync
        mount: true
        mount options: defaults
        path: /home
    -   export options: rw,sync,no_root_squash
        mount: true
        mount options: defaults
        path: /opt/ohpc/pub
    systemd name: nfs-server
tftp:
    enabled: true
    systemd name: tftp
    tftproot: /var/lib/tftpboot
warewulf:
    autobuild overlays: true
    datastore: ''
    host overlay: true
    port: 9873
    secure: false
    syslog: false
    update interval: 60
```
Call `wwctl configure --all`

### Error message

```
$ wwctl configure --all
ERROR: Couldn't parse IP address: invalid CIDR address: 10.0.0.3
```
However, if you update `ipaddr` in the configuration to `10.0.0.3/22`, the error is mitigated, but configuration of dhcpd breaks since we're rendering `http://10.0.0.3/22:9873` in `/etc/dhcpd.conf`. 

### Information on your system

This is a bug currently on the main branch
```
$ wwctl version
wwctl version:	 4.5.x-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.x-1"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Fix the issue that configuration expects CIDR address. 

## This fixes or addresses the following GitHub issues:

 - Fixes #1016

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/hpcng/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/hpcng/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
Rebased on main.

**Comment by anderbubble** [comment]
@JasonYangShadow this still causes an error starting the dhcp service when `network` is not specified in `warewulf.conf`.

```
Jan 24 21:51:08 rocky dhcpd[455775]: /etc/dhcp/dhcpd.conf line 46: semicolon expected.
Jan 24 21:51:08 rocky dhcpd[455775]:     next-server 192.168.64.1/
```

The value of `.Ipaddr` needs to always be the IP address only; not CIDR format. So if a CIDR address is provided, use that to calculate the value of `.Network` and `.Netmask` if either is not specified; but always set `.Ipaddr` internally to just the IP address part.

**Comment by anderbubble** [comment]
@JasonYangShadow I check this again, and `{{ .Ipadddr }}` is still returning CIDR format rather than the plain IP address.

In the rendered dhcpd.conf template:

```
subnet 192.168.64.0 netmask 255.255.255.0 {
    max-lease-time 120;
    range 192.168.64.50 192.168.64.99;
    next-server 192.168.64.1/24;
}
```

should be

```
subnet 192.168.64.0 netmask 255.255.255.0 {
    max-lease-time 120;
    range 192.168.64.50 192.168.64.99;
    next-server 192.168.64.1;
}
```

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow I check this again, and `{{ .Ipadddr }}` is still returning CIDR format rather than the plain IP address.
> 
> In the rendered dhcpd.conf template:
> 
> ```
> subnet 192.168.64.0 netmask 255.255.255.0 {
>     max-lease-time 120;
>     range 192.168.64.50 192.168.64.99;
>     next-server 192.168.64.1/24;
> }
> ```
> 
> should be
> 
> ```
> subnet 192.168.64.0 netmask 255.255.255.0 {
>     max-lease-time 120;
>     range 192.168.64.50 192.168.64.99;
>     next-server 192.168.64.1;
> }
> ```

it's weird that the commit is reverted to previous version somehow. I re-added the changes.

```
[root@localhost warewulf]# cat /usr/local/etc/warewulf/warewulf.conf 
WW_INTERNAL: 43
ipaddr: 192.168.211.131
netmask: 255.255.255.0
warewulf:
  port: 9873
  secure: false
  update interval: 60
  autobuild overlays: true
  host overlay: true
  syslog: false
dhcp:
  enabled: true
  range start: 192.168.211.50
  range end: 192.168.211.99
  systemd name: dhcpd
tftp:
  enabled: true
  systemd name: tftp
  ipxe:
    00:09: ipxe-snponly-x86_64.efi
    00:00: undionly.kpxe
    00:0B: arm64-efi/snponly.efi
    00:07: ipxe-snponly-x86_64.efi
nfs:
  enabled: true
  export paths:
  - path: /home
    export options: rw,sync
    mount options: defaults
    mount: true
  - path: /opt
    export options: ro,sync,no_root_squash
    mount options: defaults
    mount: false
  systemd name: nfs-server
container mounts:
  - source: /etc/resolv.conf
    dest: /etc/resolv.conf
    readonly: true

[root@localhost warewulf]# wwctl configure dhcp
Building overlay for localhost.localdomain: host
Enabling and restarting the DHCP services
[root@localhost warewulf]# cat /etc/dhcp/dhcpd.conf
# This file is autogenerated by warewulf
# Host:   localhost.localdomain
# Time:   01-30-2024 20:49:49 MST
# Source: /var/local/warewulf/overlays/host/etc/dhcpd.conf.ww

allow booting;
allow bootp;
ddns-update-style interim;
authoritative;

option space ipxe;

# Tell iPXE to not wait for ProxyDHCP requests to speed up boot.
option ipxe.no-pxedhcp code 176 = unsigned integer 8;
option ipxe.no-pxedhcp 1;

option space PXE;
option PXE.mtftp-ip    code 1 = ip-address;
option PXE.mtftp-cport code 2 = unsigned integer 16;
option PXE.mtftp-sport code 3 = unsigned integer 16;
option PXE.mtftp-tmout code 4 = unsigned integer 8;
option PXE.mtftp-delay code 5 = unsigned integer 8;

option architecture-type   code 93  = unsigned integer 16;
if exists user-class and option user-class = "iPXE" {
    filename "http://192.168.211.131:9873/ipxe/${mac:hexhyp}";
} else {

    if option architecture-type = 00:00 {
        filename "/warewulf/undionly.kpxe";
    }
    if option architecture-type = 00:07 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:09 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:0B {
        filename "/warewulf/snponly.efi";
    }
}

subnet 192.168.211.0 netmask 255.255.255.0 {
    max-lease-time 120;
    range 192.168.211.50 192.168.211.99;
    next-server 192.168.211.131;
}
```

**Comment by anderbubble** [comment]
@JasonYangShadow that might've been me mishandling a force push; if so, sorry about that. I'm glad you were able to update again.

I'll check again now.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow that might've been me mishandling a force push; if so, sorry about that. I'm glad you were able to update again.
> 
> I'll check again now.

might also be caused my previous force push. no worries at all. original logic is a bit of confusing, I think we are planning to calculate a cidr address first then update conf.Ipaddr by the valided cidr.

**Review by anderbubble — APPROVED** [review]
Looks great! I tested this with a CIDR address and no network or netmask and with a normal address and a network and netmask.

**Comment by JasonYangShadow** [comment]
> Looks great! I tested this with a CIDR address and no network or netmask and with a normal address and a network and netmask.

thanks for the verification. Have a good night.

**Pull request merged**
