### PR TITLE
Fix error when editing node

### LINKED ISSUE #1024: Error during node edit
### Steps to reproduce

```console
$ sudo wwctl node edit wwnode1
WARN   : Couldn't open :no such file or directory
ERROR  : Can't write to config exiting
```

### Error message

```
WARN   : Couldn't open :no such file or directory
ERROR  : Can't write to config exiting
```

### Information on your system

```
NAME="Rocky Linux"
VERSION="9.3 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.3 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.3"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

```
$ sudo wwctl version
wwctl version:	 4.5.x-1
rpc version: apiPrefix:"rc1"  apiVersion:"1"  warewulfVersion:"4.5.x-1"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### LINKED ISSUE #1057: node edit deletes node when warewulfd is not running
### Steps to reproduce

```
# sudo wwctl node list n1
  NODE NAME  PROFILES  NETWORK  
  n1         default            

# systemctl stop warewulfd
# sudo wwctl node edit n1
Are you sure you want to modify 1 nodes: y
ERROR  : Problem deleting nodes before modification: failed to reload warewulf daemon: Warewulf server is not running
ERROR: failed to reload warewulf daemon: Warewulf server is not running

# wwctl node list n1
  NODE NAME  PROFILES  NETWORK 
```

### Error message

_No response_

### Information on your system

Running from main.

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

Fix showing error when editing node.

## This fixes or addresses the following GitHub issues:

 - Fixes #1024
 - Fixes #1057

## Before submitting a PR, make sure you have done the following:

- [ ] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [ ] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/main/CHANGELOG.md) if necessary
- [ ] Updated [userdocs](https://github.com/hpcng/warewulf/tree/main/userdocs) if necessary
- [ ] Based this PR against the appropriate branch (typically [main](https://github.com/hpcng/warewulf/tree/main/userdocs))
- [ ] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by mslacken** [comment]
Can you please explain what exactly is fixed here?
Does #1024 happen all the time, or just if bash-completion is invoked, if yes, then I understand the bug fix.

**Comment by JasonYangShadow** [comment]
> Can you please explain what exactly is fixed here? Does #1024 happen all the time, or just if bash-completion is invoked, if yes, then I understand the bug fix.

The root cause is that `node.ConfigFile` is not initialized in this case. It looks like that it happens all the time, the ValidArgsFunction is only used for shell completion. Node initialization inside this function is not applied to RunE.

**Comment by anderbubble** [comment]
Rebased on main.

**Review by anderbubble — COMMENTED** [review]
@JasonYangShadow it's unclear to me why this addresses the issue. I imagine that it must be caching the result of node.New() somewhere, but I can't find it right now. Can you at least add a comment to `PreRunE` to indicate why this code needs to be run here? Though my actual preference would be to find out why node.New() isn't otherwise being run when needed and fix it elsewhere.

Perhaps only uncovered by this, and not caused by this: when testing this PR I encountered #1057, which is a pretty nasty data-loss bug. Can you include a fix for #1057 in this PR as well?

Thanks!

**Comment by JasonYangShadow** [comment]
when doing `CanWriteConfig` check, we can not assume that `node.ConfigFile` is initialized.

**Review by anderbubble — APPROVED** [review]
Thanks for the fixes! Looks good to me.

**Pull request merged**
