### PR TITLE
removed double entries from paths

### PR DESCRIPTION
**Pull request by mslacken**
tftproot and datadir were in paths and in the tftp and warewulf 
sections. This is completely misleading and there is so no sane
way to configure warewulf.
Also it was possibleto set version and rc in the configuration 
which is also nuts.

### CODE REVIEW

**Comment by mslacken** [comment]
@anderbubble As you should have a free time slot today, can you please merge and tag the rc1 release?

**Comment by anderbubble** [comment]
@mslacken to split into multiple PRs.

**Comment by mslacken** [comment]
@anderbubble only the path split now

**Review by anderbubble — APPROVED** [review]
lgtm. Thanks for splitting!

**Pull request merged**
