### PR TITLE
Spring cleaning - removing dead code and other source tree care

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

Holistic update and cleanup for the source tree. Mostly removing dead code using the `deadcode` utility from https://go.dev/blog/deadcode.

```
deadcode -test ./...
```

Also updated LICENSE_DEPENDENCIES.md and moved a few minor files around.

## To-do

- [x] update and re-submit after NodeInfo
- [x] use to set up a new lab install

## Reviewer checklist

The reviewer checks the following items before merging the PR.

- [ ] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [ ] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [ ] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [ ] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
@mslacken this is something I've been thinking about for a while, but I hadn't found a good tool to do it with. Tonight I found `deadcode`, which seems to do what I've been looking for.

There's a fair bit removed here, so I understand if it sparks some concern. Some of the removed code is reasonably expected, just unused; for now, I took the tact that if it's not tested then it's more risk than benefit. But if  code was in the testsuite then I considered it used, even if it's not used anywhere else.

I see there's some linter failures, so I'll address those.

Let me know what you think.

**Comment by mslacken** [comment]
Prince Arthas might not be happy with this.
Besides from that, having less coffee is always better and a great idea.
Can we postpone this after we have: 
* 4.5.1
* Merged in the dracut code
* Removed NodeInfo
Especially having removed NodeInfo will create a lot more of dead code.

I also would like to ask you if there is a tool with which we can reduce vendor depencies?

**Comment by anderbubble** [comment]
Definitely fine for this to wait until after v4.5.1.

For NodeInfo, I'd say let's go ahead and merge this in, and then just do it again after the NodeInfo refactor.

I got the errors cleared.

**Comment by anderbubble** [comment]
> For NodeInfo, I'd say let's go ahead and merge this in, and then just do it again after the NodeInfo refactor.

Eh, I'm probably wrong. This can wait until after NodeInfo. This was really easy to do, and I could see it being really disruptive to the NodeInfo refactor.

**Comment by anderbubble** [comment]
Split to https://github.com/warewulf/warewulf/issues/1457.

**Comment by anderbubble** [comment]
@mslacken ready for your review, re-done on the NodeInfo changes.

**Review by mslacken — APPROVED** [review]

**Comment by anderbubble** [comment]
Thanks for the review and merge!

**Pull request merged**
