### PR TITLE
fix autodetected kernel sorting

### LINKED ISSUE #1332: fix autodetected kernel sorting
### Steps to reproduce

Warewulf does not reliably detect the most recent kernel during auto-detection.

According to @griznog:

> I'm having a faint recollection that my original problem
> seemed to be that the kernel autodetection acted as if it was sorting
> the kernel numerically to find the latest instead of the sort -V
> equivalent.

### Error message

_No response_

### Information on your system

```
$ wwctl version
wwctl version:	 4.5.1test1+129.gf2213f0e.dirty-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.1test1+129.gf2213f0e.dirty-1"
```

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by JasonYangShadow**
## Description of the Pull Request (PR):

fix autodetected kernel sorting

## This fixes or addresses the following GitHub issues:

 - Fixes #1332

## Before submitting a PR, make sure you have done the following:

- [x] Signed off on all commits (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/main/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)

### CODE REVIEW

**Review by anderbubble — CHANGES_REQUESTED** [review]
@JasonYangShadow it looks mostly good so far (I'll dig into implementation a bit more later); but can you add support for this test case?

```
diff --git a/internal/pkg/kernel/kernel_test.go b/internal/pkg/kernel/kernel_test.go
index 2c119e09..7f96da73 100644
--- a/internal/pkg/kernel/kernel_test.go
+++ b/internal/pkg/kernel/kernel_test.go
@@ -127,6 +127,13 @@ var kernelFindTests = []struct {
                expVer:      "5.14.0-427.24.1.el9_4.x86_64",
                expPath:     "/boot/vmlinuz-5.14.0-427.24.1.el9_4.x86_64.gz",
        },
+       {
+               name:        "mixed rescue / debug kernel testing",
+               prefix:      "/boot/vmlinuz-%s",
+               kernelNames: []string{"0-rescue-eb46964329b146e39518c625feab3ea0", "5.14.0-362.24.1.el9_3.aarch64", "5.14.0-427.31.1.el9_4.aarch64+debug", "5.14.0-284.30.1.el9_2.aarch64", "5.14.0-427.31.1.el9_4.aarch64"},
+               expVer:      "5.14.0-427.31.1.el9_4.aarch64",
+               expPath:     "/boot/vmlinuz-5.14.0-427.31.1.el9_4.aarch64",
+       },
 }
 
 func Test_FindKernel(t *testing.T) {
```

It should prefer non-debug kernels over debug kernels.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow it looks mostly good so far (I'll dig into implementation a bit more later); but can you add support for this test case?
> 
> ```
> diff --git a/internal/pkg/kernel/kernel_test.go b/internal/pkg/kernel/kernel_test.go
> index 2c119e09..7f96da73 100644
> --- a/internal/pkg/kernel/kernel_test.go
> +++ b/internal/pkg/kernel/kernel_test.go
> @@ -127,6 +127,13 @@ var kernelFindTests = []struct {
>                 expVer:      "5.14.0-427.24.1.el9_4.x86_64",
>                 expPath:     "/boot/vmlinuz-5.14.0-427.24.1.el9_4.x86_64.gz",
>         },
> +       {
> +               name:        "mixed rescue / debug kernel testing",
> +               prefix:      "/boot/vmlinuz-%s",
> +               kernelNames: []string{"0-rescue-eb46964329b146e39518c625feab3ea0", "5.14.0-362.24.1.el9_3.aarch64", "5.14.0-427.31.1.el9_4.aarch64+debug", "5.14.0-284.30.1.el9_2.aarch64", "5.14.0-427.31.1.el9_4.aarch64"},
> +               expVer:      "5.14.0-427.31.1.el9_4.aarch64",
> +               expPath:     "/boot/vmlinuz-5.14.0-427.31.1.el9_4.aarch64",
> +       },
>  }
>  
>  func Test_FindKernel(t *testing.T) {
> ```
> 
> It should prefer non-debug kernels over debug kernels.

thanks! I added filters so that we can filter out unneeded kernels.

**Comment by anderbubble** [comment]
Squash rebase.

**Review by griznog — APPROVED** [review]
Worked for me in testing with rescue, debug and multiple kernel versions in the image.

**Review by anderbubble — APPROVED** [review]

**Comment by anderbubble** [comment]
Thanks for the review, @griznog!

**Pull request merged**
