### PR TITLE
 Adding Netplan NIC support for Debian/Ubuntu

### LINKED ISSUE #1463: Adding Netplan NIC support for Debian/Ubuntu
### Summary

I would like to see support for default system tools in Debian/Ubuntu, such as the use of Netplan to configure network interfaces.

### Rationale

Per the Debian Netplan FAQ (https://wiki.debian.org/Netplan/FAQ):

Using Netplan gives a central location to describe simple-to-complex networking configurations that function from desktop to server and from cloud to IoT devices.

Specifically, for systems with systemd-networkd, this reliefs the user from having to configure up to three different files per device or configuration.

It provides a common and unified way to do network configuration across the distribution and brings a modern, hybrid network stack, consisting of systemd-networkd (for minimal, static server/cloud scenarios) and NetworkManager (for interactive, dynamic desktop/laptop scenarios, e.g. WiFi). All components of this Netplan + systemd-networkd/NetworkManager stack are well-tested, under active development and supported by a company. 

### Description

In testing, all that is needed is the creation of the rootfs/etc/netplan directory in the debian.interfaces and subsequent YAML file to be populated with known variables (I name it 01-netcfg.yaml.ww)

```
{{- $host := .BuildHost }}
{{- $time := .BuildTime }}
{{- $source := .BuildSource }}
{{range $devname, $netdev := .ThisNode.NetDevs -}}
{{- $filename := print $devname  }}
{{- file $filename }}
# This file is autogenerated by warewulf
# Host:   {{ $host }}
# Time:   {{ $time }}
# Source: {{ $source }}
{{ if $netdev.OnBoot.GetB -}}
{{ end -}}
network:
  version: 2
  renderer: networkd
  ethernets:
	{{$netdev.Device.Get}}:
  	addresses:
    	- {{$netdev.Ipaddr.Get}}/{{$netdev.Netmask.Get}}
#  	routes:
#    	- to: 10.10.10.0/{{$netdev.Netmask.Get}}
#      	via: {{$netdev.Gateway.Get}}
{{- end}}
```

### Additional information

The "routes" section is currently commented out, however, if Warewulf collects a defined network, the "10.10.10.0" network address could be replaced with something like "{{$netdev.Network.Get}}" and thus routing is defined in the Netplan config. 

Further, since the Netplan config file can handle multiple interfaces and virtual interfaces, it might be possible to iterate over multiple interfaces to populate the config file.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

### PR DESCRIPTION
**Pull request by iankgt40**
## Description of the Pull Request (PR):

I would like to see support for default system tools in Debian/Ubuntu, such as the use of Netplan to configure network interfaces.

Per the Debian Netplan FAQ (https://wiki.debian.org/Netplan/FAQ):

Using Netplan gives a central location to describe simple-to-complex networking configurations that function from desktop to server and from cloud to IoT devices.

Specifically, for systems with systemd-networkd, this reliefs the user from having to configure up to three different files per device or configuration.

It provides a common and unified way to do network configuration across the distribution and brings a modern, hybrid network stack, consisting of systemd-networkd (for minimal, static server/cloud scenarios) and NetworkManager (for interactive, dynamic desktop/laptop scenarios, e.g. WiFi). All components of this Netplan + systemd-networkd/NetworkManager stack are well-tested, under active development and supported by a company.

In testing, all that is needed is the creation of the rootfs/etc/netplan directory in the debian.interfaces and subsequent YAML file to be populated with known variables (I name it 01-netcfg.yaml.ww)

## This fixes or addresses the following GitHub issues:

- Fixes #1463 

## Reviewer  checklist

The reviewer checks the following items before merging the PR.

- [x] The PR is based on the appropriate branch (typically [main](https://github.com/warewulf/warewulf/tree/main/userdocs))
- [x] All commits are "Signed off" (e.g., using `git commit --signoff`) in agreement to the [DCO](DCO.txt)
- [x] The [CHANGELOG](https://github.com/warewulf/warewulf/blob/main/CHANGELOG.md) has been updated, if necessary, and under the correct release heading
- [ ] The [userdocs](https://github.com/warewulf/warewulf/tree/main/userdocs) have been updated, if necessary
- [x] The submitter is listed in the [contributors file](https://github.com/warewulf/warewulf/blob/main/CONTRIBUTORS.md)
- [x] The test suite has been updated, if necessary

### CODE REVIEW

**Comment by iankgt40** [comment]
Ready for review ... and feel free to clean up any extraneous commits while I wrangled with whitespace :)

**Comment by anderbubble** [comment]
Thanks, @iankgt40! I'll try to get to it soon.

**Comment by anderbubble** [comment]
Rebased to main.

**Review by anderbubble — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
