### PR TITLE
sanitize wwclient url data

### LINKED ISSUE #1310: wwclient failed to get runtime overlay if there is whitespaces in Asset Tag reported by dmidecode
### Steps to reproduce

You need to have node with motherboard that have Asset Tag with whitespaces and just load it with warewulf.

### Error message

I have some old compute nodes that have 
`Asset Tag: To Be Filled By O.E.M.` in dmidecode.
I'm not 100% sure but seems like URI generated by wwclient does not sanitize whitespaces.
TCP Dump shows truncated URI:
`[Full request URI: http://xx.xx.xx.xx:9873/provision/00:xx:xx:xx:xx:xx?assetkey=To]`

Jul 23 12:29:01 node01 wwclient[332]: 2024/07/23 09:29:01 Not updating runtime overlay, got status code: 400
Jul 23 12:29:22 node01 systemd[1]: wwclient.service: start operation timed out. Terminating.
Jul 23 12:29:22 node01 wwclient[332]: termination wwclient!, terminated
Jul 23 12:29:22 node01 systemd[1]: wwclient.service: Failed with result 'timeout'.
Jul 23 12:29:22 node01 systemd[1]: Failed to start Warewulf node runtime overlay update.

### Information on your system

wwctl version:   4.5.5-1
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.5.5-1"

NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

### General information

- [X] I have run `wwctl version` and reported the contents of `/etc/os-release`
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have captured and reported relevant error messages and logs

### PR DESCRIPTION
**Pull request by griznog**
- **Sanitize/escape asset tag strings from dmidecode.**
- **Update CHANGELOG.md**

## Description of the Pull Request (PR):

When `wwclient` falls back to `dmidecode` it's possible to get values which
have spaces and posisbly other characters not friendly to URLs. This PR uses
the `net/url` package to properly escape the `dmidecode` result for the asset
tag.

- Closes #1310

### CODE REVIEW

**Comment by griznog** [comment]
Not I only fixed the asset tag because that was breaking `wwinit` on my ROcky 9 VM test nodes which were returning "Not Specified". There might be other places where escaping the values to be safe would be useful.

**Comment by snehring** [comment]
applied this on top of 4.5.5 to resolve issues in our environment with "Not Specified" being sent as the asset tag on several nodes. Solved the issue.

**Comment by anderbubble** [comment]
I think I'm going to go ahead and merge this, since it reportedly resolve the immediate issue; but I'll submit an additional PR for v4.5.7 where I try to fix it more generally. First pass here:

https://github.com/anderbubble/warewulf/tree/sanitize-wwclient-url-data

**Review by anderbubble — APPROVED** [review]

**Comment by anderbubble** [comment]
Follow-up PR at https://github.com/warewulf/warewulf/pull/1350.

**Pull request merged**
